name: Create Release

on:
  push:
    tags:
      - 'v*'
      - '*-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create release directory
      run: |
        mkdir -p release
        
    - name: Copy project files to release
      run: |
        # Copy main project files
        cp index.html release/
        cp index.css release/
        cp index.js release/
        cp jquery.min.js release/
        cp tailwind.min.css release/
        
        # Copy image assets
        cp *.png release/ 2>/dev/null || true
        
        # Copy img directory if it exists
        if [ -d "img" ]; then
          cp -r img release/
        fi
        
    - name: Create zip file
      run: |
        cd release
        zip -r ../captive-portal-${{ github.ref_name }}.zip .
        cd ..
        
    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Captive Portal Release ${{ github.ref_name }}" \
          --notes "Automated release of captive portal project.
          
        Version: ${{ github.ref_name }}
        Commit: ${{ github.sha }}
        
        This release contains the complete captive portal static files ready for deployment." \
          ./captive-portal-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}