name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create release directory
      run: |
        mkdir -p release
        
    - name: Copy project files to release
      run: |
        # Copy main project files
        cp index.html release/
        cp index.css release/
        cp index.js release/
        cp jquery.min.js release/
        cp tailwind.min.css release/
        
        # Copy img directory if it exists
        if [ -d "img" ]; then
          cp -r img release/
        fi
        
    - name: Create zip file
      run: |
        cd release
        if [[ "${{ github.ref_name }}" == "copilot/fix-13" ]]; then
          BUILD_NUMBER=$((${{ github.run_number }} - 1))
          zip -r ../cspb-admin-captive-portal.1.0.$BUILD_NUMBER.zip .
        else
          zip -r ../captive-portal-v1.0.${{ github.run_number }}.zip .
        fi
        cd ..
        
    - name: Create Release
      run: |
        if [[ "${{ github.ref_name }}" == "copilot/fix-13" ]]; then
          BUILD_NUMBER=$((${{ github.run_number }} - 1))
          gh release create cspb-admin-captive-portal.1.0.$BUILD_NUMBER \
            --title "CSPB Admin 1.0.$BUILD_NUMBER" \
            --notes "CSPB Admin Portal Release - Username/Password Authentication
            
          This release contains the CSPB Admin authentication portal with:
          • Username and password authentication form
          • Interactive WiFi usage rules modal
          • Professional CSPB branding and styling
          • Smooth modal animations
          • Error message modals for validation
          
          Version: 1.0.$BUILD_NUMBER
          Build: $BUILD_NUMBER
          Commit: ${{ github.sha }}
          
          This release contains the complete CSPB Admin portal static files ready for deployment." \
            ./cspb-admin-captive-portal.1.0.$BUILD_NUMBER.zip
        else
          gh release create v1.0.${{ github.run_number }} \
            --title "Captive Portal Release v1.0.${{ github.run_number }}" \
            --notes "Automated release of captive portal project.
            
          Version: 1.0.${{ github.run_number }}
          Build: ${{ github.run_number }}
          Commit: ${{ github.sha }}
          
          This release contains the complete captive portal static files ready for deployment." \
            ./captive-portal-v1.0.${{ github.run_number }}.zip
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}